function result = analyze_truss(nodes, members, E, areas, F, constrainedDofs, yieldStrength, density)
%ANALYZE_TRUSS Complete linear-elastic 2D truss analysis.
[u, reactions, K] = solve_displacements(nodes, members, E, areas, F, constrainedDofs);
member = calculate_member_results(nodes, members, E, areas, u, yieldStrength, density);
nodeDisplacement = hypot(u(1:2:end), u(2:2:end));
result = struct('u', u, 'reactions', reactions, 'K', K, 'member', member, ...
    'nodeDisplacement', nodeDisplacement, 'maxDisplacement', max(nodeDisplacement), ...
    'maxTension', max([0; member.force(member.force > 0)]), ...
    'maxCompression', abs(min([0; member.force(member.force < 0)])), ...
    'maxStress', max(abs(member.stress)), 'minFOS', min(member.fos), ...
    'criticalMember', find(abs(member.stress) == max(abs(member.stress)), 1), ...
    'totalMass', member.totalMass);
end
